name: Deploy to GH Pages

on:
  push:
    branches: [ "feb2025" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - run: |
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
        rm -rf node_modules/
        npm i
        npm run deploy
