name: Deploy to GH Pages

on:
  push:
    branches: [ "feb2025" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Deploy
      env:
        user_name: github-actions@github.com
        user_email: github-actions
        github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        rm -rf node_modules/
        npm i
        npm run deploy
