name: Render index on branch

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:

jobs:
  render-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Render HTML
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: ./README.md
          output_dir: src
          build_html: true
          build_pdf: true
          template: src/templates/index.html
          extend_default_theme: true
      - name: Move Files
        run: |
            cp srcREADME.html src/index.html
            cp srcREADME.pdf src/index.pdf
      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git stash
          git pull origin ${{ github.base_ref || github.ref_name }}
          git stash apply
          git add src/
          git commit -m "Generated update to index.html and index.pdf"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.base_ref || github.ref_name }}