name: Render resume on branch

on:
  push:
    branches-ignore: ["main"]
    paths: ["README.md"]
  workflow_dispatch:

jobs:
  render-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Render PDF
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: ./README.md
          output_dir: assets
          build_html: false
          build_pdf: true
          extend_default_theme: true
      - name: Move Files
        run: |
            cp assetsREADME.pdf assets/pdf/resume.pdf
      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git stash
          git pull origin ${{ github.base_ref || github.ref_name }}
          git stash apply
          git add assets/
          git commit -m "Generated update to index.pdf"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.base_ref || github.ref_name }}